name: karolos
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - numpy=1.23
  - pip
  - python=3.8
  - pytorch=1.13.1
  - pytorch-cuda
  - tensorboard
  - tqdm
  - pip:
    - gym
    - pybullet
    - scipy
    - klampt
