name: karolos
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - numpy=1.19.5
  - pip=20.3.3
  - python=3.8.6
  - pytorch=1.7.1
  - tensorboard=2.4.1
  - tqdm=4.56.0
  - pip:
    - gym==0.18.0
    - pybullet==3.0.8
    - scipy==1.6.0
